apiVersion: v1
kind: Service
metadata:
  name: nodeinfo
  labels:
    app: nodeinfo
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31119
  selector:
    app: nodeinfo
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nodeinfo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodeinfo
    spec:
      containers:
      - name: nodeinfo
        image: functions/nodeinfo:latest-armhf
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
