apiVersion: v1
kind: Service
metadata:
  name: python
  labels:
    app: python
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31299
  selector:
    app: python
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: arm32v7/python:latest
        imagePullPolicy: Always
        command: ["python3"]
        args: ["-m", "http.server", "8080"]
        ports:
        - containerPort: 8080
          protocol: TCP
