apiVersion: v1
kind: Service
metadata:
  name: wordcount
  labels:
    app: wordcount
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 31125
  selector:
    app: wordcount
---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: wordcount
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wordcount
    spec:
      containers:
      - name: wordcount
        image: functions/alpine:latest-armhf
        imagePullPolicy: Always
        command: ["fwatchdog"]
        env:
        - name: fprocess
          value: wc
        ports:
        - containerPort: 8080
          protocol: TCP
